#pragma once
#include "SyntaxTree.hpp"
#include "Name.hpp"
#include "Statements.hpp"
#include "Statement.hpp"
#include "Function.hpp"
#include "Input.hpp"
#include <stdio.h>
#include <stdlib.h>
#include <conio.h>